name: Sync Upstream

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: "Fork Sync Test Mode"
        type: boolean
        default: false
  watch:
    types:
      - started

jobs:
  sync:
    name: Sync Upstream
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    outputs:
      SHOULD_BUILD: ${{ steps.sync.outputs.has_new_commits }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GH_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: zed-industries/zed

  build:
    needs: sync
    uses: ./.github/workflows/windows_build.yml
    if: ${{ needs.sync.outputs.SHOULD_BUILD == 'true' }}
