name: Windows Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 120
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Install requirement
        run: |
          rustup update
          rustup target add wasm32-wasi

      - name: Build Zed
        run: cargo build --locked --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: "target/release/*.exe"
