name: Windows Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: cargo clippy
        run: cargo xtask clippy

      - name: Build Zed
        # run: cargo build -p zed
        run: cargo build --locked --release --target x86_64-pc-windows-msvc

      # - name: Create MSI installer
      #   run: |
      #     cargo install cargo-wix
      #     cargo wix -p zed --nocapture --target x86_64-pc-windows-msvc || true

      - name: Upload the built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: |
            target/x86_64-pc-windows-msvc/release/*.exe
            target/wix/*.msi
